version: '3'
services:
  app:
    build: .
    container_name: cloud_usage_app  
    depends_on:
      - assessment_service
    networks:
      - cloud_network

  assessment_service:
    image: mrksdh/assessment  
    container_name: assessment_container 
    ports:
      - "8080:8080"
    networks:
      - cloud_network

networks:
  cloud_network:
    driver: bridge
